name: Deploy to OCI VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # instalar git si no está
            if ! command -v git &> /dev/null; then
              sudo apt update && sudo apt install git -y
            fi

            # clonar repo si no existe
            if [ ! -d "/home/ubuntu/netservices" ]; then
              git clone https://github.com/dakardu/3tier-container-architecture.git /home/ubuntu/netservices
            fi

            cd /home/ubuntu/netservices

            # actualizar código
            git pull

            # levantar contenedores
            docker compose down || true
            docker compose up -d --build
